apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: kafka
spec:
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9092
      nodePort: 31092
  selector:
    app: kafka