apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka-cluster
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
  clusterIP: None
  selector:
    app: kafka